In [25]:
import numpy as np

In [21]:
import pandas as pd

In [22]:
from google.colab import drive

In [23]:
drive.mount('/content/gdrive/',force_remount=True)

Mounted at /content/gdrive/

In [26]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
!mkdir "/content/gdrive/MyDrive/colab Notebooks/data"

mkdir: cannot create directory ‘/content/gdrive/MyDrive/colab Notebooks/data’: No such file or directory

In [7]:
import os
# List contents of MyDrive to check for 'colab Notebooks'
print(os.listdir('/content/gdrive/MyDrive'))

['Colab Notebooks', 'hcsw-induction-checklist-and-resources.docx', '15092023_RESULTS AND DISCUSSIONS_THESIS2 - Copy.docx', 'CV_ONILUDE_HYDROGEL_POLYMERS.pdf', 'CV_Onilude_112125_3.pdf']

In [24]:
pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.2 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 4.1 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 4.5 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

In [18]:
import pandas as pd

In [27]:
from chembl_webresource_client.new_client import new_client

In [28]:
target = new_client.target

In [29]:
target_query=target.search('BRCA2')

In [30]:
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Lys-63-specific deubiquitinase BRCC36,18.0,False,CHEMBL4105965,"[{'accession': 'P46736', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Homo sapiens,BRCA2 and CDKN1A-interacting protein,16.0,False,CHEMBL6067087,"[{'accession': 'Q9P287', 'component_descriptio...",SINGLE PROTEIN,9606

In [31]:
selected_target=targets.target_chembl_id[0]
selected_target

'CHEMBL4105965'

In [32]:
activity=new_client.activity

In [37]:
results=activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [34]:
df1=pd.DataFrame.from_dict(results)

In [42]:
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,Active,18229160,[],CHEMBL4049715,Inhibition of BRCC36 (unknown origin) using Di...,B,None,None,BAO_0000201,...,Homo sapiens,Lys-63-specific deubiquitinase BRCC36,9606,None,None,INH,None,UO_0000187,None,None

In [43]:
df1.standard_type.unique()

array(['Inhibition'], dtype=object)

In [44]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

In [48]:
!cp bioactivity_raw_data.csv "/content/gdrive/MyDrive/colab Notebooks/data"

cp: failed to access '/content/gdrive/MyDrive/colab Notebooks/data': Transport endpoint is not connected

In [51]:
import shutil

In [52]:
import os

In [53]:
source = "bioactivity_raw_data.csv"
destination_folder = "/content/drive/MyDrive/colab Notebooks/data"

In [54]:
os.makedirs(destination_folder, exist_ok=True)

In [55]:
shutil.copy(source, destination_folder)

'/content/drive/MyDrive/colab Notebooks/data/bioactivity_raw_data.csv'

In [57]:
print("File copied successfully!")

File copied successfully!

In [68]:
!fusermount -u /content/gdrive 2> /dev/null

In [69]:
!fusermount -u /content/drive  2> /dev/null

In [73]:
!cp bioactivity_raw_data.csv"/content/gdrive/My Drive/Colab/Notebooks/bioactivity/data"

cp: missing destination file operand after 'bioactivity_raw_data.csv/content/gdrive/My Drive/Colab/Notebooks/bioactivity/data'
Try 'cp --help' for more information.